aliveai.create_bot({
		name="folk1",
		texture="aliveai_folk1.png",
		arm=3,
		--on_step=function(self,dtime)-- used when testing functions
		--	return self
		--end,
		--on_click=function(self,clicker)
		--	aliveai.lookat(self,clicker:getpos(),true)
		--end
})
aliveai.create_bot({
		name="folk2",
		texture="aliveai_folk2.png",
})
aliveai.create_bot({
		name="folk3",
		texture="aliveai_folk3.png",
})
aliveai.create_bot({
		name="folk4",
		texture="aliveai_folk4.png",
		work_helper=1,
})
aliveai.create_bot({
		name="folk5",
		texture="aliveai_folk5.png",
		light=-1,
		stealing=1,
		steal_chanse=2,
		talking=0,
		smartfight=0,
		fighting=0,
		lowest_light=9,
})
aliveai.create_bot({
		name="folk6",
		texture="aliveai_folk6.png",
})
aliveai.create_bot({
		name="folk7",
		texture="aliveai_folk7.png",
})
aliveai.create_bot({
		name="folk8",
		texture="aliveai_folk8.png",
})
aliveai.create_bot({
		name="folk9",
		texture="aliveai_folk9.png",
		hp=30,
		light=-1,
		stealing=1,
		steal_chanse=5,
		lowest_light=5,
})
aliveai.create_bot({
		name="folk10",
		texture="aliveai_folk10.png",
})
aliveai.create_bot({
		name="folk11",
		texture="aliveai_folk11.png",
})
aliveai.create_bot({
		name="folk12",
		texture="aliveai_folk12.png",
})
aliveai.create_bot({
		name="folk13",
		texture="aliveai_folk13.png",
		hp=30,
})
aliveai.create_bot({
		name="folk14",
		texture="aliveai_folk14.png",
		hp=50,
		dmg=8,
		work_helper=1,
})
aliveai.create_bot({
		name="folk15",
		texture="aliveai_folk15.png",
		hp=15,
})